### ISSUE TITLE
JOSS Review - Python requirement version in docs

### ISSUE THREAD

**Issue by blakeaw** [temmy222/PyTOUGHREACT#10]
This Issue has been raised as a part of the PyTOUGHREACT JOSS Review at: https://github.com/openjournals/joss-reviews/issues/6486

The Python version is given as >=3.7 in the README, but this is missing from the Dependencies section of the docs: https://pytoughreact.readthedocs.io/en/latest/dependencies.html

Instead, I see the following on my end: ```Python: pandas <https://pandas.pydata.org/> _ library``` 
Should that be something like ```Python: 3.7 or greater```? Can you double-check?

**Comment by blakeaw** [comment]
I also see that there are specific versions for the other dependencies in the pyproject.toml: https://github.com/temmy222/PyTOUGHREACT/blob/master/pyproject.toml ; e.g., `numpy>=1`

However, these requirements aren't specified in the README or docs. It could be worth including those details in the Dependencies section of the docs.

**Comment by temmy222** [comment]
Thanks for the comments. This has been corrected.
