### ISSUE TITLE
JOSS Review - Non-code contributing author

### ISSUE THREAD

**Issue by blakeaw** [temmy222/PyTOUGHREACT#11]
This Issue has been raised as a part of the PyTOUGHREACT JOSS Review at: https://github.com/openjournals/joss-reviews/issues/6486

Can you clarify the contributions of the corresponding author? I see @frank1010111 asked about this already in the review thread: https://github.com/openjournals/joss-reviews/issues/6486#issuecomment-1998824404. Could you let me know if you've already addressed this? If so, can you point me to the relevant response? Thanks.

**Comment by temmy222** [comment]
Hi @blakeaw. Yes, the corresponding author was responsible for conceptualization, paper revision, supervision and funding. The corresponding author didn't write any of the code.
