### ISSUE TITLE
JOSS Review: Missing Community Guidelines

### ISSUE THREAD

**Issue by blakeaw** [temmy222/PyTOUGHREACT#20]
This Issue has been raised as a part of the PyTOUGHREACT JOSS Review at: https://github.com/openjournals/joss-reviews/issues/6486

The requirements for community guidelines are:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

It looks like number 1 is covered by the Contributing sections of the README and docs: https://pytoughreact.readthedocs.io/en/latest/contributing.html

However, I don't see any guidelines regarding the second two items `2) Report issues or problems with the software 3) Seek support`.

**Comment by blakeaw** [comment]
You might also consider adding a CONTRIBUTING.md file to the repo that includes all the relevant community guidelines.
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file

**Comment by temmy222** [comment]
Hi @blakeaw . I added community guidelines to both the documentation and the repo. The documentation has also been changed to the master sub domain here - https://pytoughreact.readthedocs.io/en/master/contributing.html

**Comment by blakeaw** [comment]
@temmy222, cool. However, I guess the Documentation part of the readme needs to be updated now:

> Documentation
> 
> Documentation can be found here https://pytoughreact.readthedocs.io/en/latest/

The original readthedocs link now returns a 404 error.
