### ISSUE TITLE
JOSS review: documentation improvements

### ISSUE THREAD

**Issue by frank1010111** [temmy222/PyTOUGHREACT#7]
This is part of a [JOSS review](https://github.com/openjournals/joss-reviews/issues/6486).

I have identified a few issues with documentation. Apologies for the long list.
- In [Why PyTOUGHREACT](https://pytoughreact.readthedocs.io/en/latest/technical.html#why-pytoughreact), the link to PyTOUGH is dead: <https://github.com/acroucher/PyTOUGH/blob/master/doc/PyTOUGH-guide.pdf>
- There are no docstrings for 
  - [Chemical Kinetic Properties](https://pytoughreact.readthedocs.io/en/latest/chemical.html#chemical-kinetic-properties),
  - [Chemical Mineral composition](https://pytoughreact.readthedocs.io/en/latest/chemical.html#chemical-mineral-composition), 
  - [Chemical Mineral Zone](https://pytoughreact.readthedocs.io/en/latest/chemical.html#chemical-mineral-zone), 
  - [Chemical Permeability Porosity Zone](https://pytoughreact.readthedocs.io/en/latest/chemical.html#chemical-permeability-porosity-zone), 
  - any [exceptions](https://pytoughreact.readthedocs.io/en/latest/exceptions.html#exceptions-class)
  - The [Grid](https://pytoughreact.readthedocs.io/en/latest/pytoughreact.model.html#pytoughreact.model.grid.Grid) object, which seems important
  - [Relative permeability](https://pytoughreact.readthedocs.io/en/latest/exceptions.html#exceptions-class)
  - [Results for Experimental Data](https://pytoughreact.readthedocs.io/en/latest/results.html#results-for-experimental-data)
  - [Results for t2result](https://pytoughreact.readthedocs.io/en/latest/results.html#results-for-t2result)
  - [Utilities](https://pytoughreact.readthedocs.io/en/latest/utilities.html#utilities-class)
  - [Wrappers](https://pytoughreact.readthedocs.io/en/latest/wrapper.html)
- Docstring confusion
  - Most of the docstrings provide insufficient information to use the method, class, or function. If I might suggest putting yourself in the mindset of a new PhD student, excited to be using your tool to run Tough React but overwhelmed by all the options you've given them and trying to understand, say, the way to set biomass compositions.
  - The docstrings for the [Constants Class](https://pytoughreact.readthedocs.io/en/latest/constants.html) are just copies of the MIT license
  - Several of the parameters in [React Writing](https://pytoughreact.readthedocs.io/en/latest/writers.html#react-writing) are missing explanations
  - Parameters are also missing from [Biomass Composition](https://pytoughreact.readthedocs.io/en/latest/chemical.html#biomass-composition). I'm not sure why the docstring says "rock type".
  - It is unclear whether [duplicate_index](https://pytoughreact.readthedocs.io/en/latest/results.html#pytoughreact.results.result_tough_3.ResultTough3.duplicate_index) ascertains whether an index is duplicated or creates a duplicate index
  - It is unclear what type of file is read by [read_file](https://pytoughreact.readthedocs.io/en/latest/results.html#pytoughreact.results.result_tough_3.ResultTough3.read_file)
- In [Contributions](https://pytoughreact.readthedocs.io/en/latest/contributing.html), how does one run `flake8`? Are any flake8 plugins used? Is it run under default settings?
- Also in Contributions, it would be nice to link to the [Developer Notes](https://pytoughreact.readthedocs.io/en/latest/developer.html)
- In [Dependencies](https://pytoughreact.readthedocs.io/en/latest/dependencies.html), the list of dependencies is different than in the [pyproject.toml](https://github.com/temmy222/PyTOUGHREACT/blob/4ef403e2993424c7b5e97dee9ef6522a272e8617/pyproject.toml#L14-L20)
- In the [README badge](https://github.com/temmy222/PyTOUGHREACT/blob/4ef403e2993424c7b5e97dee9ef6522a272e8617/README.md?plain=1#L205) and PyPI site, the license is LGPL
![image](https://github.com/temmy222/PyTOUGHREACT/assets/4694479/3ce0bd8d-1815-420e-bd86-844fb023cb04)
In other places, it's listed as MIT. I think the LICENSE file that says MIT has primacy, but it would be nice to be sure
- The paper is roughly 2,000 words, but [JOSS suggests](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) 250-1000 words.

I haven't gotten to the tutorial yet, so I don't have any comments or suggestions there right now.

**Comment by frank1010111** [comment]
Another suggestion on [Contributions](https://pytoughreact.readthedocs.io/en/latest/contributing.html), could you include information on how to install `flake8` and `pytest`?

**Comment by temmy222** [comment]
Hi. I am working on resolving the issues raised

**Comment by frank1010111** [comment]
Thank you,

It would also be very helpful for the docs and readme to talk about the TOUGHREACT binaries. I'm guessing you have to at least get the [TOUGHREACT binary](https://tough.lbl.gov/licensing-download/toughreact-licensing-download/). But also maybe [tough2](https://tough.lbl.gov/licensing-download/itough2-price-sheet/) for tmvoc?

**Comment by frank1010111** [comment]
Okay, I'm getting to the tutorials now. My first question concerns these lines:

https://github.com/temmy222/PyTOUGHREACT/blob/d57a245128f79d3a8a7fdcd866eca1b44f36f146/documentation/tutorial.rst?plain=1#L54-L76

These properties t2react of don't appear to be [documented](https://pytoughreact.readthedocs.io/en/latest/writers.html#pytoughreact.writers.react_writing.t2react). Are they required? What  is the react parameter dictionary? What keys are allowed and what do they mean?

**Comment by frank1010111** [comment]
For the grid class part:

https://github.com/temmy222/PyTOUGHREACT/blob/d57a245128f79d3a8a7fdcd866eca1b44f36f146/documentation/tutorial.rst?plain=1#L85-L91

What do the values for `rocktype` mean? `rocktype` is documented nowhere I can find, and it appears to be pulled from PyTOUGH, which has [limited information](https://github.com/acroucher/PyTOUGH/blob/master/t2grids.py#L20-L22) on the properties. Things like the units of each measure are missing even from their code.

Then you delete a rock type and add in sand. What is the default rock type? Does it always get deleted?

What are the differences between this grid that you call t2reactgrid, and the Grid object? It took me a while to figure out that they were distinct entities.

**Comment by temmy222** [comment]
Hi @frank1010111 . Thanks for your review. I believe I have fixed most of the issues you raised on the documentation. Please let me know if I missed any. I will begin fixing the issues you raised with the tutorials immediately.

**Comment by blakeaw** [comment]
Hi @temmy222, I'm not sure if you have addressed this already, but I wanted to note that I agree with @frank1010111's comment about insufficient information in most docstrings: 

> Most of the docstrings provide insufficient information to use the method, class, or function.

I ran into this problem while trying to follow along with the tutorial. I thought maybe the API docs would help, but they are lacking descriptions of the different objects (or have only very short ones). In particular, for each class, I'd recommend describing the object it represents along with some context on its purpose in the simulations. 

If you have addressed this already please let me know, as any changes don't seem to be reflected in the latest version of the docs on readthedocs.

**Comment by temmy222** [comment]
Hi @frank1010111. Thanks for your review

Here are comments to your first comments on this issue

1) Link to PyTOUGH has been corrected
2) Documentation updated to correct all mentioned points
3) Contributions updated
4) Dependencies same as pyproject.toml
5) License updated to show MIT everywhere
6) Paper content itself is less than 1000 words. The examples are added which make it appear to be more than 1000 words

**Comment by frank1010111** [comment]
Hi Temmy,

Thank you for these changes. I am seeing improvement in the documentations.

Unfortunately, there have also been some breakages in the examples. I am trying to get things working again, as documented here: https://github.com/temmy222/PyTOUGHREACT/pull/17

Is this the [thddem.dat](https://github.com/temmy222/PyTOUGHREACT/blob/f509b58b04668f46f4f07a650d5c0eafb0f99ee2/thddem.dat) file that the code seems to need? There doesn't appear to be one in the current repository, so I had to go searching through the history.

**Comment by temmy222** [comment]
Thank you for the fix @frank1010111. Yes, that is the required thddem.dat. I removed it from the repo because it seems to have been changed. Users can specify their database themselves
