### ISSUE TITLE
JOSS review: testing

### ISSUE THREAD

**Issue by frank1010111** [temmy222/PyTOUGHREACT#8]
Hello again, this is an issue related to [the JOSS review](https://github.com/openjournals/joss-reviews/issues/6486).

Neither [Contributions](https://pytoughreact.readthedocs.io/en/latest/contributing.html) nor the readme give sufficient information to run the associated tests.

Could you include information on how to install `flake8` and `pytest`? 

Installing pytest with pip and running it leads to this message:
```sh
$ pytest
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=pytoughreact
```

That seems to indicate that pytest-cov is another testing dependency. Looking at the [tox.ini](https://github.com/temmy222/PyTOUGHREACT/blob/master/tox.ini#L24) seems to confirm that. This also leads me to wonder: Do you recommend using `tox` to run the unit tests?

Looking at the tests themselves, there don't appear to be any that run the simulations or check simulation outputs:
```sh
$ rg \\.run test 
test/test_pytoughreact_bio.py
121:        # bio.run(simulator='tmvoc', runlocation='')

test/test_pytoughreact_react.py
339:        # react.run(writeSolute, simulator='treacteos1.exe')
```

**Comment by temmy222** [comment]
Hi @frank1010111 . The README has been updated to show how to install flake8 and pytests in order to run the test. The idea of the tests is not to run the simulations or check the outputs but to check that the software writes to the required file and can read all values from the files into the classes in the software.

**Comment by matthewfeickert** [comment]
> The idea of the tests is not to run the simulations or check the outputs but to check that the software writes to the required file and can read all values from the files into the classes in the software.

@temmy222 Do the tests actually test the software at all? If they only test reading and writing this is not enough.

**Comment by frank1010111** [comment]
Can we reopen this issue? @matthewfeickert makes my argument more eloquently than I could.

**Comment by matthewfeickert** [comment]
> Can we reopen this issue? 

@temmy222 Please reopen. Though you will also need to find a way to address the concerns raised in https://github.com/openjournals/joss-reviews/issues/6486#issuecomment-2121848175.

**Comment by temmy222** [comment]
@matthewfeickert  @frank1010111. Additional tests have been added to the software which have improved the code coverage

**Comment by matthewfeickert** [comment]
@temmy222 Please reread https://github.com/temmy222/PyTOUGHREACT/issues/8#issuecomment-2087739837 and then reopen this Issue.

Please also keep my comments in https://github.com/openjournals/joss-reviews/issues/6486#issuecomment-2121848175 in mind when interacting with the reviewers.
