### ISSUE TITLE
JOSS Review - Link to License in README

### ISSUE THREAD

**Issue by blakeaw** [temmy222/PyTOUGHREACT#9]
This Issue has been raised as a part of the PyTOUGHREACT JOSS Review at: https://github.com/openjournals/joss-reviews/issues/6486

Hi @temmy222,

The license link in the README points to the MIT license template on Choose a License: https://choosealicense.com/licenses/mit/
Is this on purpose, or should that link to your copy of the license stored in your repository?

**Comment by temmy222** [comment]
Thank you for the catch. This has been corrected
